### ISSUE TITLE
Cycle detected in ormolu: nix develop fails

### ISSUE THREAD

**Issue by siraben** [ethereum/hevm#308] opened 2023-07-11 13:36 UTC
I get the following error when I run `nix develop` on aarch64-darwin on 8b0c6792f09a890a13ed1e9713f639410209fc56.

```
$ nix develop
error: cycle detected in build of '/nix/store/djzdfnsljcqzj1q03aawha7i319gybla-ormolu-0.5.3.0.drv' in the references of output 'bin' from output 'out'
```

**Comment by d-xo** [comment] 2023-07-12 08:45
hm, seems like this is something we should report upstream to nixpkgs?

**Comment by msooseth** [comment] 2023-09-20 13:58
This is no longer an issue on `main` on my install. While `nix` is supposed to be reproducible, that may not always hold -- is it still an issue on your side @siraben ?

**Comment by msooseth** [comment] 2023-12-21 13:30
I am closing, as we didn't get a response and we can't reproduce.

**Closed by msooseth** 2023-12-21 13:30 UTC
